### PR TITLE
Added XML output and Xpath filtering - 2nd attempt

### PR DESCRIPTION
**Pull request by jeffbrl**
I added the ability for the user to specify XML output using --format xml at the command line. I also added the optional use of xpath expressions in the commands file.

An example line from the commands file might look like this -

show route 2600::/64 % //rt-entry

The op command is separated from the xpath expression by a '%' character.

### CODE REVIEW

**Comment by jeffbrl** [comment]
Any idea when you guys might get some time for the regression tests needed to merge my PR?

**Comment by nprintz** [comment]
Sorry it's been a while, things got busy at the end of 2014. Geoff and I had some time to work on the next version of Jaide and do testing. We're looking to pull this in very soon, and drop the next version. Hopefully by the end of this week.

**Comment by nprintz** [comment]
We have pulled in this feature, and updated jaide to v1.1.0 (a415a82). Thanks for all the help Jeff.

**Comment by jeffbrl** [comment]
Thanks for the merging my feature, guys. I'm glad to contribute a small bit to an impressive software package like jaide.

**Pull request closed without merging**
